/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type CyclingSession = {
  /**
   * @format int32
   */
  cyclingSessionId?: number;
  /**
   * @format date-time
   */
  date?: string;
  /**
   * @format int32
   */
  duration?: number;
  /**
   * @format int32
   */
  avg_Watt?: number;
  /**
   * @format int32
   */
  max_Watt?: number;
  /**
   * @format int32
   */
  avg_Cadence?: number;
  /**
   * @format int32
   */
  mAx_Cadence?: number;
  trainingType?: string;
  comment?: string;
};

export type Equipment = {
  /**
   * @format int32
   */
  equipmentId?: number;
  deviceType?: string[];
  isAvailable?: boolean;
};

export type FitnessProgram = {
  programCode?: string;
  name?: string;
  target?: string;
  /**
   * @format date-time
   */
  startDate?: string;
  /**
   * @format int32
   */
  maxMembers?: number;
  members?: Member[];
};

export type Member = {
  /**
   * @format int32
   */
  memberId?: number;
  /**
   * @minLength 1
   */
  firstName: string;
  /**
   * @minLength 1
   */
  lastName: string;
  /**
   * @minLength 1
   */
  email: string;
  /**
   * @minLength 1
   */
  city: string;
  /**
   * @format date-time
   */
  birthday: string;
  interests?: string[] | null;
  memberType: MemberType;
  fitnessPrograms?: FitnessProgram[];
  reservations?: Reservation[];
  cyclingSessions?: CyclingSession[];
  runningSessions?: RunningSession[];
};

/**
 * @format int32
 */
export type MemberType = 0 | 1 | 2;

export type Reservation = {
  /**
   * @format int32
   */
  reservationId?: number;
  equipment?: Equipment;
  timeSlot?: TimeSlot;
  /**
   * @format date-time
   */
  date?: string;
};

export type RunningSession = {
  /**
   * @format int32
   */
  runningSessionId?: number;
  /**
   * @format date-time
   */
  date?: string;
  /**
   * @format int32
   */
  duration?: number;
  /**
   * @format int32
   */
  avg_Speed?: number;
  details?: RunningSessionDetail[];
};

export type RunningSessionDetail = {
  /**
   * @format int32
   */
  seq_nr?: number;
  /**
   * @format int32
   */
  interval_Time?: number;
  /**
   * @format int32
   */
  interval_Speed?: number;
};

export type TimeSlot = {
  /**
   * @format int32
   */
  timeSlotId?: number;
  /**
   * @format date-time
   */
  startTime?: string;
  /**
   * @format date-time
   */
  endTime?: string;
  partOfDay?: string;
};
